/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLOCKCOPY_H_RPCGEN
#define _BLOCKCOPY_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct pba_write_params {
	quad_t pba_src;
	quad_t pba_dst;
	int nbytes;
};
typedef struct pba_write_params pba_write_params;

struct get_server_ios {
	u_quad_t server_read_time;
	u_quad_t server_write_time;
	u_quad_t server_other_time;
};
typedef struct get_server_ios get_server_ios;

#define BLOCKCOPY_PROG 0x34567890
#define BLOCKCOPY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define WRITE_PBA 1
extern  int * write_pba_1(pba_write_params *, CLIENT *);
extern  int * write_pba_1_svc(pba_write_params *, struct svc_req *);
#define GET_TIME 2
extern  get_server_ios * get_time_1(void *, CLIENT *);
extern  get_server_ios * get_time_1_svc(void *, struct svc_req *);
#define RESET_TIME 3
extern  void * reset_time_1(void *, CLIENT *);
extern  void * reset_time_1_svc(void *, struct svc_req *);
extern int blockcopy_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define WRITE_PBA 1
extern  int * write_pba_1();
extern  int * write_pba_1_svc();
#define GET_TIME 2
extern  get_server_ios * get_time_1();
extern  get_server_ios * get_time_1_svc();
#define RESET_TIME 3
extern  void * reset_time_1();
extern  void * reset_time_1_svc();
extern int blockcopy_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_pba_write_params (XDR *, pba_write_params*);
extern  bool_t xdr_get_server_ios (XDR *, get_server_ios*);

#else /* K&R C */
extern bool_t xdr_pba_write_params ();
extern bool_t xdr_get_server_ios ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_BLOCKCOPY_H_RPCGEN */
