/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blockcopy.h"

bool_t
xdr_pba_write_params (XDR *xdrs, pba_write_params *objp)
{
	register int32_t *buf;

	 if (!xdr_quad_t (xdrs, &objp->pba_src))
		 return FALSE;
	 if (!xdr_quad_t (xdrs, &objp->pba_dst))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->nbytes))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_get_server_ios (XDR *xdrs, get_server_ios *objp)
{
	register int32_t *buf;

	 if (!xdr_u_quad_t (xdrs, &objp->server_read_time))
		 return FALSE;
	 if (!xdr_u_quad_t (xdrs, &objp->server_write_time))
		 return FALSE;
	 if (!xdr_u_quad_t (xdrs, &objp->server_other_time))
		 return FALSE;
	return TRUE;
}
