/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _BLOCKCOPY_RANDOM_H_RPCGEN
#define _BLOCKCOPY_RANDOM_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAX_BATCH 1024

struct pba_write_params {
	int64_t pba_src;
	int64_t pba_dst;
	int nbytes;
};
typedef struct pba_write_params pba_write_params;
#ifdef __cplusplus
extern "C" bool_t xdr_pba_write_params(XDR *, pba_write_params*);
#elif __STDC__
extern  bool_t xdr_pba_write_params(XDR *, pba_write_params*);
#else /* Old Style C */
bool_t xdr_pba_write_params();
#endif /* Old Style C */


struct pba_batch_params {
	int64_t pba_srcs[MAX_BATCH];
	int64_t pba_dsts[MAX_BATCH];
	uint32 count;
	uint32 block_size;
};
typedef struct pba_batch_params pba_batch_params;
#ifdef __cplusplus
extern "C" bool_t xdr_pba_batch_params(XDR *, pba_batch_params*);
#elif __STDC__
extern  bool_t xdr_pba_batch_params(XDR *, pba_batch_params*);
#else /* Old Style C */
bool_t xdr_pba_batch_params();
#endif /* Old Style C */


struct get_server_ios {
	u_int64_t server_read_time;
	u_int64_t server_write_time;
	u_int64_t server_other_time;
};
typedef struct get_server_ios get_server_ios;
#ifdef __cplusplus
extern "C" bool_t xdr_get_server_ios(XDR *, get_server_ios*);
#elif __STDC__
extern  bool_t xdr_get_server_ios(XDR *, get_server_ios*);
#else /* Old Style C */
bool_t xdr_get_server_ios();
#endif /* Old Style C */


#define BLOCKCOPY_PROG ((rpc_uint)0x34567890)
#define BLOCKCOPY_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define WRITE_PBA ((rpc_uint)1)
extern "C" int * write_pba_1(pba_write_params *, CLIENT *);
extern "C" int * write_pba_1_svc(pba_write_params *, struct svc_req *);
#define GET_TIME ((rpc_uint)2)
extern "C" get_server_ios * get_time_1(void *, CLIENT *);
extern "C" get_server_ios * get_time_1_svc(void *, struct svc_req *);
#define RESET_TIME ((rpc_uint)3)
extern "C" void * reset_time_1(void *, CLIENT *);
extern "C" void * reset_time_1_svc(void *, struct svc_req *);
#define WRITE_PBA_BATCH ((rpc_uint)4)
extern "C" int * write_pba_batch_1(pba_batch_params *, CLIENT *);
extern "C" int * write_pba_batch_1_svc(pba_batch_params *, struct svc_req *);

#elif __STDC__
#define WRITE_PBA ((rpc_uint)1)
extern  int * write_pba_1(pba_write_params *, CLIENT *);
extern  int * write_pba_1_svc(pba_write_params *, struct svc_req *);
#define GET_TIME ((rpc_uint)2)
extern  get_server_ios * get_time_1(void *, CLIENT *);
extern  get_server_ios * get_time_1_svc(void *, struct svc_req *);
#define RESET_TIME ((rpc_uint)3)
extern  void * reset_time_1(void *, CLIENT *);
extern  void * reset_time_1_svc(void *, struct svc_req *);
#define WRITE_PBA_BATCH ((rpc_uint)4)
extern  int * write_pba_batch_1(pba_batch_params *, CLIENT *);
extern  int * write_pba_batch_1_svc(pba_batch_params *, struct svc_req *);

#else /* Old Style C */
#define WRITE_PBA ((rpc_uint)1)
extern  int * write_pba_1();
extern  int * write_pba_1_svc();
#define GET_TIME ((rpc_uint)2)
extern  get_server_ios * get_time_1();
extern  get_server_ios * get_time_1_svc();
#define RESET_TIME ((rpc_uint)3)
extern  void * reset_time_1();
extern  void * reset_time_1_svc();
#define WRITE_PBA_BATCH ((rpc_uint)4)
extern  int * write_pba_batch_1();
extern  int * write_pba_batch_1_svc();
#endif /* Old Style C */

#endif /* !_BLOCKCOPY_RANDOM_H_RPCGEN */
