/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "blockcopy_random.h"

bool_t
xdr_pba_write_params(xdrs, objp)
	XDR *xdrs;
	pba_write_params *objp;
{

	if (!xdr_int64_t(xdrs, &objp->pba_src))
		return (FALSE);
	if (!xdr_int64_t(xdrs, &objp->pba_dst))
		return (FALSE);
	if (!xdr_int(xdrs, &objp->nbytes))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_pba_batch_params(xdrs, objp)
	XDR *xdrs;
	pba_batch_params *objp;
{

	if (!xdr_vector(xdrs, (char *)objp->pba_srcs, MAX_BATCH, sizeof(int64_t), (xdrproc_t)xdr_int64_t))
		return (FALSE);
	if (!xdr_vector(xdrs, (char *)objp->pba_dsts, MAX_BATCH, sizeof(int64_t), (xdrproc_t)xdr_int64_t))
		return (FALSE);
	if (!xdr_uint32(xdrs, &objp->count))
		return (FALSE);
	if (!xdr_uint32(xdrs, &objp->block_size))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_get_server_ios(xdrs, objp)
	XDR *xdrs;
	get_server_ios *objp;
{

	if (!xdr_u_int64_t(xdrs, &objp->server_read_time))
		return (FALSE);
	if (!xdr_u_int64_t(xdrs, &objp->server_write_time))
		return (FALSE);
	if (!xdr_u_int64_t(xdrs, &objp->server_other_time))
		return (FALSE);
	return (TRUE);
}
